# Generated by Django 5.0 on 2023-12-14 06:55
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categoria_post',
            field=models.ForeignKey(
                default=1, 
                on_delete=django.db.models.deletion.CASCADE, 
                to='posts.categorias',
                ),
            preserve_default=False,
        ),
    ]
